# Generated by Django 2.1.7 on 2019-03-11 02:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='None of the above', max_length=30)),
                ('is_mentor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('answers', models.ManyToManyField(to='testapp.Answer')),
                ('comments', models.ManyToManyField(to='testapp.Comment')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='TimeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('votes', models.IntegerField()),
                ('voters', models.ManyToManyField(to='testapp.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='attendees',
            field=models.ManyToManyField(to='testapp.Profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='classes',
            field=models.ManyToManyField(to='testapp.Classes'),
        ),
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(to='testapp.Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Profile'),
        ),
        migrations.AddField(
            model_name='classes',
            name='attendees',
            field=models.ManyToManyField(to='testapp.Profile'),
        ),
        migrations.AddField(
            model_name='classes',
            name='comments',
            field=models.ManyToManyField(to='testapp.Comment'),
        ),
        migrations.AddField(
            model_name='classes',
            name='times',
            field=models.ManyToManyField(to='testapp.TimeChoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='comments',
            field=models.ManyToManyField(to='testapp.Comment'),
        ),
        migrations.AddField(
            model_name='answer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Profile'),
        ),
    ]
