# Generated by Django 2.1.7 on 2019-03-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='questions',
            field=models.ManyToManyField(to='testapp.Questions'),
        ),
    ]
